sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hernantain/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hernantain/docker-react npm run test